options:
  max-warnings: 0
files:
  include: 'src/**/*.scss'
formatter:
  - 'stylish'
rules:
  class-name-format:
    - 2
    -
      convention: 'hyphenatedbem'
  placeholder-name-format:
    - 2
    -
      convention: 'hyphenatedbem'
  declarations-before-nesting: 2
  empty-args:
    - 1
    -
      include: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  force-attribute-nesting: 1
  force-element-nesting: 2
  force-pseudo-nesting: 1
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
  indentation:
    - 2
    -
      size: 'tab'
  property-sort-order:
    - 1
    -
      ignore-custom-properties: true

